[versions]
kotlin = "2.0.0"
wgpu = "v0.0.0.2"
download = "5.6.0"
jreleaser = "1.13.1"


[libraries]
download = { module = "de.undercouch.download:de.undercouch.download.gradle.plugin", version.ref = "download" }
kotlin-multiplatform = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jreleaser-plugin = { module = "org.jreleaser:org.jreleaser.gradle.plugin", version.ref = "jreleaser" }


[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
