name: Tests

on:
  push:
    branches: [ main, 'release/**', 'feature/**'  ]
  pull_request:
    branches: [ main, 'release/**', 'feature/**'  ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y libc6-dev-i386 libglfw3-dev
      - name: set llvm Path On macos
        if: matrix.os == 'macos-14'
        run: echo "LIBCLANG_PATH=/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr" >> $GITHUB_ENV
      - name: set llvm Path On windows
        if: matrix.os == 'windows-latest'
        run: echo "LIBCLANG_PATH=\"C:\Program Files\LLVM\"" >> $GITHUB_ENV
      - name: print architecture
        run: uname -m
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
          cache: 'gradle'
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build, test & Analyse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: |
          echo "clang path :"
          echo $LIBCLANG_PATH
          gradle wrapper
          ./gradlew fetch-native-dependencies build check --stacktrace
      - name: package
        run: ./gradlew assemble --stacktrace
